# Generated by Django 5.1.7 on 2025-03-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Photograph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("legend", models.CharField(max_length=512)),
                ("description", models.TextField()),
                ("photo", models.CharField(max_length=128)),
            ],
        ),
    ]
