# Generated by Django 5.1.7 on 2025-03-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_photograph_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="photograph",
            name="published",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="photograph",
            name="category",
            field=models.CharField(
                choices=[
                    ("NEBULA", "nebula"),
                    ("STAR", "star"),
                    ("GALLAXY", "gallaxy"),
                    ("PLANET", "planet"),
                ],
                default="",
                max_length=128,
            ),
        ),
    ]
