# Generated by Django 5.1.7 on 2025-03-18 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0003_photograph_published_alter_photograph_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="photograph",
            name="photo_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
