# Generated by Django 5.1.7 on 2025-03-21 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0005_alter_photograph_photo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="photograph",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="photograph",
            name="category",
            field=models.CharField(
                choices=[
                    ("NEBULA", "nebula"),
                    ("STAR", "star"),
                    ("galaxy", "galaxy"),
                    ("PLANET", "planet"),
                ],
                default="",
                max_length=128,
            ),
        ),
    ]
