# Generated by Django 5.1.7 on 2025-03-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="photograph",
            name="category",
            field=models.CharField(
                choices=[
                    ("NEBULA", "nebulla"),
                    ("STAR", "star"),
                    ("GALLAXY", "gallaxy"),
                    ("PLANET", "planet"),
                ],
                default="",
                max_length=128,
            ),
        ),
    ]
