# Generated by Django 5.1.7 on 2025-03-26 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0006_photograph_user_alter_photograph_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photograph",
            name="category",
            field=models.CharField(
                choices=[
                    ("NEBULA", "nebula"),
                    ("STAR", "star"),
                    ("GALAXY", "galaxy"),
                    ("PLANET", "planet"),
                ],
                default="",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="photograph",
            name="photo_date",
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="photograph",
            name="published",
            field=models.BooleanField(default=True),
        ),
    ]
